# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://bhaveshpatil:bhavesh123@cluster0.khwkbbt.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=todoapp

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web=INFO
